version: 2

project_name: kv

before:
  hooks:
    - go mod download

release:
  prerelease: "false"

env:
  - CGO_ENABLED=0

builds:
  - id: linux
    main: ./cmd/kv
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/yousysadmin/kv/pkg.Version={{.Version }}

  - id: osx
    main: ./cmd/kv
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/yousysadmin/kv/pkg.Version={{.Version }}

  - id: windows
    main: ./cmd/kv
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/yousysadmin/kv/pkg.Version={{.Version }}

archives:
  - name_template: >-
      {{ .Binary }}_v{{ .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ['zip']

checksum:
  name_template: "checksums.sha256"

snapshot:
  version_template: "{{ .Tag }}-devel"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    maintainer: Oleksii YouSysAdmin
    homepage: https://github.com/yousysadmin/kv
    description: Get AWS credentials via Jumpcloud SAML
    license: "MIT"
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/nfpm/copyright
        file_info:
          mode: 0644

dockers:
  # linux/amd64
  - ids: [linux]
    image_templates:
      - ghcr.io/yousysadmin/kv:{{ .Version }}-amd64
    dockerfile: build/docker/Dockerfile
    # extra_files:
    #   - build/docker/entrypoint.sh
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.source=https://github.com/YouSysAdmin/kv
      - --label=org.opencontainers.image.version={{ .Version }}

  # linux/arm64
  - ids: [linux]
    image_templates:
      - ghcr.io/yousysadmin/kv:{{ .Version }}-arm64
    dockerfile: build/docker/Dockerfile
    # extra_files:
    #   - build/docker/entrypoint.sh
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.source=https://github.com/YouSysAdmin/kv
      - --label=org.opencontainers.image.version={{ .Version }}

docker_manifests:
  - name_template: ghcr.io/yousysadmin/kv:{{ .Version }}
    image_templates:
      - ghcr.io/yousysadmin/kv:{{ .Version }}-amd64
      - ghcr.io/yousysadmin/kv:{{ .Version }}-arm64
  - name_template: ghcr.io/yousysadmin/kv:latest
    image_templates:
      - ghcr.io/yousysadmin/kv:{{ .Version }}-amd64
      - ghcr.io/yousysadmin/kv:{{ .Version }}-arm64
